<?php $this->headTitle('Dashboard'); ?>

<div class="list-group">
    <a href="<?=$this->url('section', ['id' => 0])?>" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 text-uppercase">0. kopējais</h5>
            <small>0/1 уроков</small>
        </div>
        <small>Общее</small>
    </a>
    <a href="<?=$this->url('section', ['id' => 1])?>" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 text-uppercase">1. prieks iepazīties</h5>
            <small>0/6 уроков</small>
        </div>
        <small>Приятно познакомиться</small>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 text-uppercase">2. no visas pasaules</h5>
            <small>0/6 уроков</small>
        </div>
        <small>Со всего мира</small>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 text-uppercase">3. pilsēta un laukos</h5>
            <small>0/5 уроков</small>
        </div>
        <small>Город и за городом</small>
    </a>
    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 text-uppercase">4. mana māja un ģimene</h5>
            <small>0/6 уроков</small>
        </div>
        <small>Мой дом и семья</small>
    </a>
</div>

<div class="row justify-content-md-center">
    <div class="offset-lg-0 col-lg-6 offset-md-0 col-md-8 offset-sm-1 col-sm-10 offset-0 col-12 align-self-center py-3">
        <hr class="my-2 mt-5">
        <p>
            <small class="text-muted font-weight-light">Kucheryaviy production &copy;<?=date('Y')?></small>
        </p>
    </div>
</div>
