<?php $this->headTitle('Dashboard'); ?>

<div class="jumbotron offset-lg-3 col-lg-6 offset-md-2 col-md-8 offset-sm-1 col-sm-10 offset-0 col-12 align-self-center py-3">
    <h2>Laipni lūdzam <span class="text-success">iegaumē.com</span></h2>
    <p>
        iegaumē - с латышшского 'запоминай'. Сервис по запоминанию лашышских слов.
    </p>
</div>

<div class="row justify-content-md-center">
    <div class="offset-lg-0 col-lg-6 offset-md-0 col-md-8 offset-sm-1 col-sm-10 offset-0 col-12 align-self-center py-3">
        <hr class="my-2 mt-5">
        <p>
            <small class="text-muted font-weight-light">Kucheryaviy production &copy;<?=date('Y')?></small>
        </p>
    </div>
</div>
