<?php $this->headTitle('Dashboard'); ?>
<?php /** @var Domain\Entity\Section[] $sections */ ?>
<div class="list-group">
    <a href="<?=$this->url('section', ['id' => 0])?>" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 text-uppercase">0. <?=$sections[99]->getTitle('lv')?></h5>
            <small>0/<?=$sections[99]->getLessonsCount()?> уроков</small>
        </div>
        <small><?=$sections[99]->getTitle('ru')?></small>
    </a>

    <?php unset($sections[99]); ?>

    <?php foreach ($sections as $section): ?>
        <a href="<?=$this->url('section', ['id' => $section->getId()])?>" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1 text-uppercase"><?=$section->getId()?>. <?=$section->getTitle('lv')?></h5>
                <small>0/<?=$section->getLessonsCount()?> уроков</small>
            </div>
            <small><?=$section->getTitle('ru')?></small>
        </a>
    <?php endforeach; ?>
</div>

<div class="row justify-content-md-center">
    <div class="offset-lg-0 col-lg-6 offset-md-0 col-md-8 offset-sm-1 col-sm-10 offset-0 col-12 align-self-center py-3">
        <hr class="my-2 mt-5">
        <p>
            <small class="text-muted font-weight-light">Kucheryaviy production &copy;<?=date('Y')?></small>
        </p>
    </div>
</div>
