<?php $this->headTitle('Урок 1а'); ?>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="<?=$this->url('section', ['id' => 0])?>">1. Prieks iepazīties</a></li>
        <li class="breadcrumb-item active" aria-current="page">a. Iepazīšanas</li>
    </ol>
</nav>

<ul class="nav nav-pills justify-content-center">
    <li class="nav-item">
        <a class="nav-link" href="<?=$this->url('lesson', ['sectionId' => 1, 'id' => 'a', 'mode' => 'cards'])?>">Карточки</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="<?=$this->url('lesson', ['sectionId' => 1, 'id' => 'a', 'mode' => 'learn'])?>">Учи</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="<?=$this->url('lesson', ['sectionId' => 1, 'id' => 'a', 'mode' => 'write'])?>">Пиши</a>
    </li>
</ul>

<div class="row mt-3">
    <div class="col">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-light">9 Осталось&nbsp;&nbsp;&nbsp;<i class="fa fa-arrow-right"></i></button>
            <button type="button" class="btn btn-light pl-2">0 Знаком&nbsp;&nbsp;&nbsp;<i class="fa fa-arrow-right"></i></button>
            <button type="button" class="btn btn-light pl-1">1 Изучено</button>
        </div>
    </div>
</div>
<div class="row mt-2" style="height: 270px;">
    <div class="col d-flex">
        <a class="card border-primary align-self-stretc w-100 animated fadeInRight" href="javascript:void(0)" id="word-1">
            <div class="card-body text-dark d-flex align-items-start flex-column">
                <h2 class="card-title mb-auto">Raksti</h2>
                <input type="text" class="form-control">
                <small class="form-text text-muted">Напиши ответ здесь.</small>
            </div>
        </a>
        <a class="card border-primary align-self-stretc w-100 animated d-none" href="javascript:void(0)" id="word-2">
            <div class="card-body text-dark d-flex align-items-start flex-column">
                <h2 class="card-title mb-auto">Huyaksti</h2>
                <button type="button" class="btn btn-outline-secondary btn-sm mb-1">Secondary1</button>
                <button type="button" class="btn btn-outline-secondary btn-sm mb-1">Secondary2</button>
                <button type="button" class="btn btn-outline-secondary btn-sm mb-1">Secondary3</button>
                <button type="button" class="btn btn-outline-secondary btn-sm mb-1">Secondary4</button>
            </div>
        </a>
    </div>
</div>
<div class="row mt-2">
    <div class="col d-flex justify-content-end">
        <button type="button" class="btn btn-primary btn-lg" id="next-card-btn">Ответить <i class="fa fa-chevron-right"></i></button>
    </div>
</div>
