<?php
$this->headTitle('Логин');
?>

<div class="row">
    <div class="offset-lg-3 col-lg-6 offset-md-2 col-md-8 offset-sm-1 col-sm-10 offset-0 col-12">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    <div class="form-group">
                        <label for="login">Идентифицируй себя</label>
                        <input name="login" type="text" class="form-control" id="login">
                        <small class="form-text text-muted">Введи что угодно, например, имя или е-майл</small>
                    </div>

                    <button type="submit" class="btn btn-primary btn-lg btn-block">Войти</button>
                </form>
            </div>
        </div>
    </div>
</div>
