<?php
$this->headTitle('Регистрация');
if (!isset($username)) {
    $username = '';
}
?>

<div class="row">
    <div class="offset-lg-3 col-lg-6 offset-md-2 col-md-8 offset-sm-1 col-sm-10 offset-0 col-12">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    <div class="form-group">
                        <label for="username">Идентифицируй себя</label>
                        <input name="username" type="text" class="form-control" id="username" value="<?=$username?>">
                        <?php if (!empty($error)): ?>
                            <small class="form-text text-danger"><?=$error?></small>
                        <?php else: ?>
                            <small class="form-text text-muted">Введи что угодно, например, имя или е-майл</small>
                        <?php endif; ?>
                    </div>
                    <div class="form-group">
                        <label for="password">Пароль</label>
                        <input name="password" type="password" class="form-control" id="password">
                    </div>

                    <button type="submit" class="btn btn-primary btn-lg btn-block">Создать аккаунт</button>
                </form>
            </div>
        </div>
    </div>
</div>
