<?php
$this->headTitle('Раздел 1');
/** @var \Domain\Entity\Section $section */
/** @var \Domain\Entity\Lesson[] $lessons */
?>

<?=$this->breadcrumb($section->getId())?>

<div class="list-group">
    <?php foreach($lessons as $lesson): ?>
        <a href="<?=$this->url('lesson', ['sectionId' => $section->getId(), 'lessonId' => $lesson->getId(), 'mode' => 'cards'])?>" class="list-group-item list-group-item-action flex-column align-items-start">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1"><?=$lesson->getIndexLetter()?>. <?=$lesson->getTitle('lv')?></h5>
                <small>0/<?=$lesson->getWordsCount()?> слов</small>
            </div>
            <small><?=$lesson->getTitle('ru')?></small>
        </a>
    <?php endforeach; ?>
</div>
