<?php $this->headTitle('Раздел 1'); ?>

<div class="list-group">
    <a href="<?=$this->url('lesson', ['sectionId' => 1, 'id' => 'a', 'mode' => 'cards'])?>" class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1 text-uppercase">a. iepazīšanas</h5>
            <small>0/13 слов</small>
        </div>
        <small>Знакомство</small>
    </a>
</div>
