version: "3.1"
services:

    db:
      image: mysql:8.0
      container_name: iegaume-db
      working_dir: /application
      volumes:
        - ../:/application
        - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=111
        - MYSQL_DATABASE=iegaume
        - MYSQL_USER=iegaume
        - MYSQL_PASSWORD=111
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: iegaume-webserver
      working_dir: /application
      volumes:
          - ../:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php:
      build: docker/php-fpm
      container_name: iegaume-php
      working_dir: /application
      volumes:
        - ../:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

