<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.0.6/css/all.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css');
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.3.1.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <?=$this->headTitle('iegaumē')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <link href="/custom.css" media="screen" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
</head>
<body class="pt-2">
    <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-around align-items-center ">
            <div class="col-5">
                <a class="text-success h3" href="/">iegaumē.com</a>
            </div>
            <div class="col-5 d-flex justify-content-end align-items-center">
                <div class="p-1"><?=$this->getAuthorizedUser()->getLogin()?></div>
                <a class="btn btn-sm btn-outline-secondary" href="<?=$this->url('logout')?>">
                    Logout <i class="fa fa-sign-out-alt"></i>
                </a>
            </div>
        </div>
    </header>
    <main role="main" class="container">
        <div class="content">
            <main class="container">
                <?=$this->content?>
            </main>
        </div>
    </main>

    <?=$this->inlineScript()?>
</body>
</html>
