<?php
/** @var int $remaining */
/** @var int $familiar */
/** @var int $mastered */
?>

<div class="row mt-3">
    <div class="col">
        <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
            <button type="button" class="btn btn-light"><?=$remaining?> Осталось&nbsp;&nbsp;&nbsp;<i class="fa fa-arrow-right"></i></button>
            <button type="button" class="btn btn-light pl-2"><?=$familiar?> Знаком&nbsp;&nbsp;&nbsp;<i class="fa fa-arrow-right"></i></button>
            <button type="button" class="btn btn-light pl-1"><?=$mastered?> Изучено</button>
        </div>
    </div>
</div>
